# Generated by Django 3.2.16 on 2023-02-13 14:32

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MstBattleRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.CharField(blank=True, max_length=16, null=True, verbose_name='ランク')),
                ('party_name', models.CharField(max_length=256, verbose_name='パーティ名')),
                ('my_pokemon', django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, max_length=48, null=True, size=3, verbose_name='対戦時の自分ポケモン')),
                ('enemy_pokemon', django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, max_length=48, null=True, size=3, verbose_name='対戦時の相手ポケモン')),
                ('result', models.CharField(blank=True, max_length=16, null=True, verbose_name='対戦結果')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='論理削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'バトル戦績の登録',
                'db_table': 'battle_record',
            },
        ),
        migrations.CreateModel(
            name='MstPokemon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('poke_name', models.CharField(max_length=256, unique=True, verbose_name='ポケモン名')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='レベル')),
                ('personality', models.CharField(blank=True, max_length=20, null=True, verbose_name='性格')),
                ('identity', models.CharField(blank=True, max_length=30, null=True, verbose_name='個性')),
                ('item', models.CharField(blank=True, max_length=30, null=True, verbose_name='持ち物')),
                ('hp', models.IntegerField(blank=True, null=True, verbose_name='HP')),
                ('attack', models.IntegerField(blank=True, null=True, verbose_name='攻撃')),
                ('defence', models.IntegerField(blank=True, null=True, verbose_name='防御')),
                ('special_attack', models.IntegerField(blank=True, null=True, verbose_name='特殊攻撃')),
                ('special_defence', models.IntegerField(blank=True, null=True, verbose_name='特殊防御')),
                ('speed', models.IntegerField(blank=True, null=True, verbose_name='素早さ')),
                ('hp_effort', models.IntegerField(blank=True, null=True, verbose_name='HP努力値')),
                ('attack_effort', models.IntegerField(blank=True, null=True, verbose_name='攻撃努力値')),
                ('defence_effort', models.IntegerField(blank=True, null=True, verbose_name='防御努力値')),
                ('special_attack_effort', models.IntegerField(blank=True, null=True, verbose_name='特殊攻撃努力値')),
                ('special_defence_effort', models.IntegerField(blank=True, null=True, verbose_name='特殊防御努力値')),
                ('speed_effort', models.IntegerField(blank=True, null=True, verbose_name='素早さ努力値')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='論理削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ポケモンの登録',
                'db_table': 'pokemon',
            },
        ),
        migrations.CreateModel(
            name='MstParty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('party_name', models.CharField(max_length=256, verbose_name='パーティ名')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='論理削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('poke_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_api_app.mstpokemon', to_field='poke_name', verbose_name='ポケモン名')),
            ],
            options={
                'verbose_name': 'パーティの登録',
                'db_table': 'party',
            },
        ),
    ]
